import Head from 'next/head'
import {AiFillLinkedin, AiFillYoutube, AiFillInstagram, AiFillGithub} from 'react-icons/ai'
import Image from "next/image"
import avatar from "../../public/avatar.png"
import { useState } from 'react'
import Card from './card'
import SkillCard from './skillCard'
import {projects, skills} from "../../public/myData"
import Contact from './contact'
import Navbar from './navbar'
import About from './about'
import Test from './test'

export default function Home() {
  const [darkMode, setDarkMode] = useState<Boolean>(true)
  return (
    <div className={darkMode ? 'dark' : ""}>
      <Head>
        <title>Akshat Wagadre Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="images/favicon.png" />
      </Head>

      <main className='relative bg-white p-1 dark:bg-black'>

        {/* ******************* Navbar ********************* */}
        <Navbar darkMode={darkMode} setDarkMode={setDarkMode}/>
        
        {/* ******************* Home ********************* */}

        <section className=" bg-blue-200 h-auto lg:min-h-screen dark:bg-gray-900 pb-5 header">
          <div id='home' className='text-center p-10 pt-40'>
            <h2 className='text-5xl py-2 text-teal-600 lg:text-7xl font-bold'>Akshat Wagadre</h2>
            <h3 className='text-2xl py-4 dark:text-gray-300 font-bold'>Software Developer</h3>
            <p className='text-lg py-4 leading-8 text-gray-800 dark:text-gray-400'>I&apos;m a curious software developer with a strong passion for the field. I love exploring and creating!</p>
          </div>
          
        {/* ******************* Links ********************* */}
          <div className='text-5xl flex justify-center gap-12 lg:gap-16 py-3 text-gray-500'>
            <a className="hover:scale-150 transition-all" href="https://github.com/aksh4t-w" target="_blank" rel="noreferrer"><AiFillGithub/></a>
            <a className="hover:scale-150 transition-all" href="https://www.linkedin.com/in/akshat-w/" target="_blank" rel="noreferrer"><AiFillLinkedin/></a>
            <a className="hover:scale-150 transition-all" href="https://www.youtube.com/channel/UCRCtuNqoxPBYqOgwb4rPSXw" target="_blank" rel="noreferrer"><AiFillYoutube/></a>
            <a className="hover:scale-150 transition-all" href="https://www.instagram.com/akshat.w/" target="_blank" rel="noreferrer"><AiFillInstagram/></a>
          </div>
          <div className='relative mx-auto mt-10 mb-10 rounded-full w-80 h-80 lg:mt-20'>
            <div className="absolute top-0 w-80 h-80 bg-gradient-to-b from-teal-500 to-pink-600 rounded-full filter blur-sm animate-blob">
            </div>
            <Image className='absolute -top-1 rounded-full' src={avatar} alt="3D avatar of the author" style={{objectFit:"cover"}}/>
          </div>
        </section>

        {/* ******************* About ********************* */}
        <section id="about" className='mt-5 p-10 h-fit grid dark:bg-gray-900'>
          <h2 className="mb-3 text-4xl pb-2 m-auto font-extrabold text-center text-gray-900 dark:text-white border-b-4 border-pink-600">About</h2>
          <About />
        </section>

        {/* ******************* Skills ********************* */}
        <section id="skills" className='mt-5 grid'>
          <h2 className="mb-3 text-4xl pb-2 m-auto font-extrabold text-center text-gray-900 dark:text-white border-b-4 border-pink-600">Skills</h2>
          <div className='w-full grid grid-cols-2 lg:flex flex-wrap lg:gap-10 justify-center lg:w-4/6 lg:m-auto'>
            {skills.map((skill, index) => (
              <SkillCard skill = {skill} key={index}/>
            ))}
          </div>
        </section>

        {/* ******************* Projects ********************* */}
        <section id="projects" className='mt-10 grid'>
          {/* <h3 className='text-3xl py-1'></h3> */}
          <h2 className="mb-4 text-4xl pb-2 m-auto tracking-tight font-extrabold text-center text-gray-900 dark:text-white border-b-4 border-pink-600">Some of my Projects</h2>
          <div className='lg:flex flex-wrap gap-10 justify-center w-4/6 m-auto'>
            {projects.map((project, index) => (
              <Card project = {project} key={index}/>
            ))}
          </div>
        </section>
        
        {/* ******************* Contact ********************* */}
        <Contact />

        <footer className='text-center text-gray-500 dark:text-gray-400 h-10'>
          <p className="mt-4">© 2023 Akshat Wagadre</p>
        </footer>
      
        {/* <Test /> */}
      </main>
    </div>
  )
}
