import Head from 'next/head'
import {BsFillMoonStarsFill, BsFillSunFill} from 'react-icons/bs'
import {AiFillLinkedin, AiFillYoutube, AiFillInstagram, AiFillGithub} from 'react-icons/ai'
import Image from "next/image"
import avatar from "../../public/avatar.png"
import cloud2 from "../../public/images/cloud2.png"
import { useState } from 'react'
import Card from './card'
import {projects} from "../../public/myData"
import Contact from './contact'

export default function Home() {
  const [darkMode, setDarkMode] = useState(false)

  return (
    <div className={darkMode ? 'dark' : ""}>
      <Head>
        <title>Akshat Wagadre Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white p-2 dark:bg-black'>
        <section className="bg-blue-200 min-h-screen dark:bg-gray-900">
          <nav className='p-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons dark:text-gray-300'>{'{Developed by Akshat}'}</h1>
            <ul className='flex items-center'>
              {darkMode ? 
                <li><BsFillSunFill className='cursor-pointer text-2xl text-cyan-50' onClick={()=>setDarkMode(!darkMode)} /></li>
              :
                <li><BsFillMoonStarsFill className='cursor-pointer text-2xl' onClick={()=>setDarkMode(!darkMode)} /></li>
              }<li>
                <a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href={"/Resume_2.pdf"} target="_blank">Resume</a>
              </li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium'>Akshat Wagadre</h2>
            <h3 className='text-2xl py-4 dark:text-gray-300'>Software Developer</h3>
            <p className='text-lg py-4 leading-8 text-gray-800 dark:text-gray-400'>I'm a curious software developer with a strong passion for the field. I love exploring and creating!</p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
            <a href="https://github.com/aksh4t-w" target="_blank"><AiFillGithub/></a>
            <a href="https://www.linkedin.com/in/akshat-w/" target="_blank"><AiFillLinkedin/></a>
            <a href="https://www.youtube.com/channel/UCRCtuNqoxPBYqOgwb4rPSXw" target="_blank"><AiFillYoutube/></a>
            <a href="https://www.instagram.com/akshat.w/" target="_blank"><AiFillInstagram/></a>
          </div>
          <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden'>
            <Image src={avatar} alt="3D avatar of the author" fill objectFit="cover"/>
          </div>
        </section>

        <section className=''>
          {/* <h3 className='text-3xl py-1'></h3> */}
          <div className='lg:flex flex-wrap gap-10 justify-center'>
            {projects.map((project) => (
              <Card project = {project}/>
            ))}
          </div>
        </section>
      </main>
      <Contact />
    </div>
  )
}
